---
# tasks file for role-eosxd
- name: Check variables
  assert:
    that:
      - "role_eosxd_mgmt_alias is defined"
      - "role_eosxd_mount_point is defined"

- include_tasks: repos.yml

- name: Create config folder
  file:
    mode: 0755
    state: directory
    path: "/etc/eos"

- name: Configure eosxd
  template:
    mode: 0644
    src: fuse.eos.conf
    dest: /etc/eos/fuse.eos.conf

- name: Add eos.keytab file
  template:
    src: eos.keytab.j2
    dest: "{{ role_eosxd_sss_keytab_file }}"
    mode: "0400"
    owner: root
    group: root


- name: Add/remove /etc/fstab entry
  mount:
    path: "{{ role_eosxd_mount_point }}"
    src: eosxd
    opts: fsname=eos
    state: "{{ role_eosxd_fstab_state }}"
    fstype: fuse
